import type { ConnectorMeta } from "./types";

export const CORE_CONNECTORS: ConnectorMeta[] = [
  {
    id: "gmail",
    name: "Gmail",
    description: "Emails et messagerie",
    icon: "✉️",
    source: "core",
    category: "communication",
    provider: "google",
    connectAction: "google",
  },
  {
    id: "calendar",
    name: "Google Agenda",
    description: "Rendez-vous et planning",
    icon: "📅",
    source: "core",
    category: "productivity",
    provider: "google",
    connectAction: "google",
  },
  {
    id: "drive",
    name: "Google Drive",
    description: "Fichiers et documents",
    icon: "📁",
    source: "core",
    category: "storage",
    provider: "google",
    connectAction: "google",
  },
  {
    id: "slack",
    name: "Slack",
    description: "Messages d'équipe",
    icon: "💬",
    source: "core",
    category: "communication",
    provider: "slack",
    connectAction: "slack",
  },
];

export const EXTERNAL_CONNECTORS: ConnectorMeta[] = [
  { id: "notion", name: "Notion", description: "Notes et bases de données", icon: "📝", source: "external", category: "productivity" },
  { id: "linear", name: "Linear", description: "Gestion de projets", icon: "📐", source: "external", category: "project" },
  { id: "github", name: "GitHub", description: "Dépôts et pull requests", icon: "🐙", source: "external", category: "dev" },
  { id: "jira", name: "Jira", description: "Suivi de tickets", icon: "🎫", source: "external", category: "project" },
  { id: "figma", name: "Figma", description: "Design et prototypes", icon: "🎨", source: "external", category: "productivity" },
  { id: "hubspot", name: "HubSpot", description: "CRM et contacts", icon: "🤝", source: "external", category: "crm" },
  { id: "salesforce", name: "Salesforce", description: "CRM et ventes", icon: "☁️", source: "external", category: "crm" },
  { id: "asana", name: "Asana", description: "Gestion de projets", icon: "✅", source: "external", category: "project" },
  { id: "trello", name: "Trello", description: "Tableaux de tâches", icon: "📋", source: "external", category: "project" },
  { id: "dropbox", name: "Dropbox", description: "Stockage de fichiers", icon: "📦", source: "external", category: "storage" },
  { id: "onedrive", name: "OneDrive", description: "Fichiers Microsoft", icon: "💾", source: "external", category: "storage" },
  { id: "outlook", name: "Outlook", description: "Email Microsoft", icon: "📧", source: "external", category: "communication" },
  { id: "teams", name: "Microsoft Teams", description: "Chat et visio", icon: "👥", source: "external", category: "communication" },
  { id: "zoom", name: "Zoom", description: "Visioconférences", icon: "🎥", source: "external", category: "communication" },
  { id: "intercom", name: "Intercom", description: "Support client", icon: "💬", source: "external", category: "communication" },
  { id: "zendesk", name: "Zendesk", description: "Support et tickets", icon: "🎧", source: "external", category: "communication" },
  { id: "stripe", name: "Stripe", description: "Paiements et factures", icon: "💳", source: "external", category: "analytics" },
  { id: "shopify", name: "Shopify", description: "E-commerce", icon: "🛍️", source: "external", category: "analytics" },
  { id: "airtable", name: "Airtable", description: "Bases de données", icon: "📊", source: "external", category: "productivity" },
  { id: "confluence", name: "Confluence", description: "Documentation", icon: "📖", source: "external", category: "productivity" },
  { id: "clickup", name: "ClickUp", description: "Productivité", icon: "⚡", source: "external", category: "project" },
  { id: "monday", name: "Monday.com", description: "Gestion de travail", icon: "🗂️", source: "external", category: "project" },
  { id: "gitlab", name: "GitLab", description: "DevOps et CI/CD", icon: "🦊", source: "external", category: "dev" },
  { id: "bitbucket", name: "Bitbucket", description: "Dépôts Git", icon: "🪣", source: "external", category: "dev" },
  { id: "sentry", name: "Sentry", description: "Monitoring d'erreurs", icon: "🐛", source: "external", category: "dev" },
  { id: "datadog", name: "Datadog", description: "Observabilité", icon: "📈", source: "external", category: "analytics" },
  { id: "mixpanel", name: "Mixpanel", description: "Analytics produit", icon: "📉", source: "external", category: "analytics" },
  { id: "amplitude", name: "Amplitude", description: "Analytics comportemental", icon: "📊", source: "external", category: "analytics" },
  { id: "google-analytics", name: "Google Analytics", description: "Analytics web", icon: "📈", source: "external", category: "analytics" },
  { id: "twilio", name: "Twilio", description: "SMS et appels", icon: "📱", source: "external", category: "communication" },
  { id: "sendgrid", name: "SendGrid", description: "Emails transactionnels", icon: "📨", source: "external", category: "communication" },
  { id: "mailchimp", name: "Mailchimp", description: "Email marketing", icon: "🐵", source: "external", category: "communication" },
  { id: "discord", name: "Discord", description: "Chat communautaire", icon: "🎮", source: "external", category: "communication" },
  { id: "vercel", name: "Vercel", description: "Déploiement frontend", icon: "▲", source: "external", category: "dev" },
  { id: "aws", name: "AWS", description: "Infrastructure cloud", icon: "☁️", source: "external", category: "dev" },
  { id: "firebase", name: "Firebase", description: "Backend Google", icon: "🔥", source: "external", category: "dev" },
  { id: "supabase", name: "Supabase", description: "Backend open-source", icon: "⚡", source: "external", category: "dev" },
  { id: "postgres", name: "PostgreSQL", description: "Base de données", icon: "🐘", source: "external", category: "dev" },
  { id: "mongodb", name: "MongoDB", description: "Base NoSQL", icon: "🍃", source: "external", category: "dev" },
  { id: "redis", name: "Redis", description: "Cache et temps réel", icon: "🔴", source: "external", category: "dev" },
  { id: "snowflake", name: "Snowflake", description: "Data warehouse", icon: "❄️", source: "external", category: "analytics" },
  { id: "bigquery", name: "BigQuery", description: "Analytics Google", icon: "🔍", source: "external", category: "analytics" },
  { id: "tableau", name: "Tableau", description: "Visualisation de données", icon: "📊", source: "external", category: "analytics" },
  { id: "power-bi", name: "Power BI", description: "Business intelligence", icon: "📊", source: "external", category: "analytics" },
  { id: "zapier", name: "Zapier", description: "Automatisations", icon: "⚡", source: "external", category: "productivity" },
  { id: "make", name: "Make", description: "Workflows automatisés", icon: "🔄", source: "external", category: "productivity" },
  { id: "calendly", name: "Calendly", description: "Planification de rendez-vous", icon: "📆", source: "external", category: "productivity" },
  { id: "loom", name: "Loom", description: "Messages vidéo", icon: "🎬", source: "external", category: "communication" },
  { id: "miro", name: "Miro", description: "Tableaux collaboratifs", icon: "🖼️", source: "external", category: "productivity" },
  { id: "docusign", name: "DocuSign", description: "Signatures électroniques", icon: "✍️", source: "external", category: "productivity" },
];

export const ALL_CONNECTORS: ConnectorMeta[] = [...CORE_CONNECTORS, ...EXTERNAL_CONNECTORS];

export function getConnector(id: string): ConnectorMeta | undefined {
  return ALL_CONNECTORS.find((c) => c.id === id);
}
