/**
 * Catalog Generated — Auto-sync from Nango providers.yaml
 *
 * ⚠️ WARNING: This file is auto-generated by scripts/sync-nango-catalog.ts
 * Do not edit manually. Changes will be overwritten.
 *
 * This file merges Nango's provider catalog with Hearst-specific metadata.
 * It provides the raw data for lib/integrations/catalog.ts to consume.
 */

import type { ServiceDefinition, ServiceTier, IntegrationType } from "./types";

/**
 * Nango provider metadata (subset of providers.yaml).
 * Full sync not yet implemented — manual seed for Tier 3.
 */
interface NangoProviderSeed {
  id: string;
  name: string;
  categories: string[];
  auth_mode: "OAUTH2" | "API_KEY" | "BASIC";
  docs?: string;
}

/**
 * Tier 3 services — long-tail integrations.
 *
 * Previously seeded with 23 placeholder Nango entries that all had
 * `status: "planned"` and no working backend. Showing them in /apps was
 * misleading: users clicked, nothing worked.
 *
 * Long-tail providers are now surfaced through Composio's discovery layer
 * (see `ComposioConnectionsCard` and `lib/connectors/composio/discovery.ts`)
 * which only exposes apps the user has actually connected.
 *
 * If/when a provider should ship in the curated UI catalog as Tier 1/2,
 * promote it explicitly in `lib/integrations/catalog.ts`.
 */
const TIER_3_NANGO_SERVICES: Array<Partial<ServiceDefinition> & { nangoProvider: string }> = [];

/**
 * Generate full ServiceDefinition from Nango seed.
 */
function generateFromNango(seed: typeof TIER_3_NANGO_SERVICES[0]): ServiceDefinition {
  return {
    id: seed.id!,
    name: seed.name!,
    description: `Intégration ${seed.name} via Nango`,
    icon: "",
    category: seed.category!,
    tier: "tier_3" as ServiceTier,
    type: "nango" as IntegrationType,
    status: "planned",
    providerId: seed.nangoProvider,
    capabilities: seed.capabilities || ["research"],
    isConnectable: true,
  };
}

/**
 * All Tier 3 services from Nango catalog.
 * Read-only policy: these services only support read/search operations.
 */
export const NANGO_TIER_3_SERVICES: ServiceDefinition[] = TIER_3_NANGO_SERVICES.map(generateFromNango);

/**
 * Get all Nango-provided services.
 */
export function getNangoServices(): ServiceDefinition[] {
  return NANGO_TIER_3_SERVICES;
}

/**
 * Check if a service is Nango-managed (Tier 3).
 */
export function isNangoService(serviceId: string): boolean {
  return NANGO_TIER_3_SERVICES.some((s) => s.id === serviceId);
}

/**
 * TODO: Implement sync script scripts/sync-nango-catalog.ts
 * This will:
 * 1. Fetch providers.yaml from Nango
 * 2. Merge with existing Tier 1/2 services
 * 3. Generate this file automatically
 * 4. Preserve manual overrides in a separate config
 */
export const SYNC_STATUS = "manual-seed"; // "auto-sync" when script implemented
