/**
 * Catalog Generated — Auto-sync from Nango providers.yaml
 *
 * ⚠️ WARNING: This file is auto-generated by scripts/sync-nango-catalog.ts
 * Do not edit manually. Changes will be overwritten.
 *
 * This file merges Nango's provider catalog with Hearst-specific metadata.
 * It provides the raw data for lib/integrations/catalog.ts to consume.
 */

import type { ServiceDefinition, ServiceTier, IntegrationType } from "./types";

/**
 * Nango provider metadata (subset of providers.yaml).
 * Full sync not yet implemented — manual seed for Tier 3.
 */
interface NangoProviderSeed {
  id: string;
  name: string;
  categories: string[];
  auth_mode: "OAUTH2" | "API_KEY" | "BASIC";
  docs?: string;
}

/**
 * Tier 3 services — long-tail integrations via Nango.
 * These are read-only, generic UI, deep-link to native app.
 */
const TIER_3_NANGO_SERVICES: Array<Partial<ServiceDefinition> & { nangoProvider: string }> = [
  // Communication & Social
  { id: "discord", name: "Discord", nangoProvider: "discord", category: "communication", capabilities: ["messaging"] },
  { id: "zoom", name: "Zoom", nangoProvider: "zoom", category: "communication", capabilities: ["messaging"] },
  { id: "teams", name: "Microsoft Teams", nangoProvider: "microsoft-teams", category: "communication", capabilities: ["messaging"] },
  { id: "linkedin", name: "LinkedIn", nangoProvider: "linkedin", category: "communication", capabilities: ["messaging"] },

  // Productivity
  { id: "confluence", name: "Confluence", nangoProvider: "confluence", category: "productivity", capabilities: ["files"] },
  { id: "miro", name: "Miro", nangoProvider: "miro", category: "productivity", capabilities: ["design"] },
  { id: "docusign", name: "DocuSign", nangoProvider: "docusign", category: "productivity", capabilities: ["automation"] },

  // CRM
  { id: "salesforce", name: "Salesforce", nangoProvider: "salesforce", category: "crm", capabilities: ["crm"] },
  { id: "pipedrive", name: "Pipedrive", nangoProvider: "pipedrive", category: "crm", capabilities: ["crm"] },
  { id: "intercom", name: "Intercom", nangoProvider: "intercom", category: "communication", capabilities: ["messaging"] },
  { id: "zendesk", name: "Zendesk", nangoProvider: "zendesk", category: "support", capabilities: ["support"] },

  // Dev & Infra
  { id: "gitlab", name: "GitLab", nangoProvider: "gitlab", category: "dev", capabilities: ["developer_tools"] },
  { id: "bitbucket", name: "Bitbucket", nangoProvider: "bitbucket", category: "dev", capabilities: ["developer_tools"] },
  { id: "vercel", name: "Vercel", nangoProvider: "vercel", category: "dev", capabilities: ["developer_tools"] },
  { id: "sentry", name: "Sentry", nangoProvider: "sentry", category: "dev", capabilities: ["developer_tools"] },

  // Analytics
  { id: "mixpanel", name: "Mixpanel", nangoProvider: "mixpanel", category: "analytics", capabilities: ["research"] },
  { id: "amplitude", name: "Amplitude", nangoProvider: "amplitude", category: "analytics", capabilities: ["research"] },
  { id: "segment", name: "Segment", nangoProvider: "segment", category: "analytics", capabilities: ["research"] },

  // Finance
  { id: "quickbooks", name: "QuickBooks", nangoProvider: "quickbooks", category: "finance", capabilities: ["finance"] },
  { id: "xero", name: "Xero", nangoProvider: "xero", category: "finance", capabilities: ["finance"] },
  { id: "shopify", name: "Shopify", nangoProvider: "shopify", category: "commerce", capabilities: ["commerce"] },

  // Storage
  { id: "dropbox", name: "Dropbox", nangoProvider: "dropbox", category: "storage", capabilities: ["files"] },
  { id: "onedrive", name: "OneDrive", nangoProvider: "onedrive", category: "storage", capabilities: ["files"] },
];

/**
 * Generate full ServiceDefinition from Nango seed.
 */
function generateFromNango(seed: typeof TIER_3_NANGO_SERVICES[0]): ServiceDefinition {
  return {
    id: seed.id!,
    name: seed.name!,
    description: `Intégration ${seed.name} via Nango`,
    icon: "",
    category: seed.category!,
    tier: "tier_3" as ServiceTier,
    type: "nango" as IntegrationType,
    status: "planned",
    providerId: seed.nangoProvider,
    capabilities: seed.capabilities || ["research"],
    isConnectable: true,
  };
}

/**
 * All Tier 3 services from Nango catalog.
 * Read-only policy: these services only support read/search operations.
 */
export const NANGO_TIER_3_SERVICES: ServiceDefinition[] = TIER_3_NANGO_SERVICES.map(generateFromNango);

/**
 * Get all Nango-provided services.
 */
export function getNangoServices(): ServiceDefinition[] {
  return NANGO_TIER_3_SERVICES;
}

/**
 * Check if a service is Nango-managed (Tier 3).
 */
export function isNangoService(serviceId: string): boolean {
  return NANGO_TIER_3_SERVICES.some((s) => s.id === serviceId);
}

/**
 * TODO: Implement sync script scripts/sync-nango-catalog.ts
 * This will:
 * 1. Fetch providers.yaml from Nango
 * 2. Merge with existing Tier 1/2 services
 * 3. Generate this file automatically
 * 4. Preserve manual overrides in a separate config
 */
export const SYNC_STATUS = "manual-seed"; // "auto-sync" when script implemented
